2024-05-18 15:21:30,663 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2024-05-18 15:21:30,663 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Configure stats pid to 20812
2024-05-18 15:21:30,663 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ernst\.config\wandb\settings
2024-05-18 15:21:30,663 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Loading settings from c:\Users\ernst\Documents\02-Work\01-Projects\MANTRA\wandb\settings
2024-05-18 15:21:30,663 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-18 15:21:30,663 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-18 15:21:30,663 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-18 15:21:30,663 INFO    MainThread:20812 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\ernst\Documents\02-Work\01-Projects\MANTRA\wandb\run-20240518_152130-z6rci8yv\logs\debug.log
2024-05-18 15:21:30,664 INFO    MainThread:20812 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\ernst\Documents\02-Work\01-Projects\MANTRA\wandb\run-20240518_152130-z6rci8yv\logs\debug-internal.log
2024-05-18 15:21:30,664 INFO    MainThread:20812 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000290A08F1090>
2024-05-18 15:21:30,664 INFO    MainThread:20812 [wandb_init.py:init():564] calling init triggers
2024-05-18 15:21:30,664 INFO    MainThread:20812 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-05-18 15:21:30,664 INFO    MainThread:20812 [wandb_init.py:init():614] starting backend
2024-05-18 15:21:30,664 INFO    MainThread:20812 [wandb_init.py:init():618] setting up manager
2024-05-18 15:21:30,667 INFO    MainThread:20812 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-18 15:21:30,675 INFO    MainThread:20812 [wandb_init.py:init():624] backend started and connected
2024-05-18 15:21:30,683 INFO    MainThread:20812 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-05-18 15:21:30,683 INFO    MainThread:20812 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-18 15:21:30,683 INFO    MainThread:20812 [wandb_init.py:init():716] updated telemetry
2024-05-18 15:21:30,707 INFO    MainThread:20812 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-05-18 15:21:31,061 ERROR   MainThread:20812 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-18 15:21:31,150 ERROR   MainThread:20812 [wandb_init.py:init():1184] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\wandb_init.py", line 1166, in init
    run = wi.init()
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-18 15:21:53,780 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2024-05-18 15:21:53,780 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Configure stats pid to 20812
2024-05-18 15:21:53,780 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ernst\.config\wandb\settings
2024-05-18 15:21:53,780 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Loading settings from c:\Users\ernst\Documents\02-Work\01-Projects\MANTRA\wandb\settings
2024-05-18 15:21:53,780 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-18 15:21:53,780 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-18 15:21:53,780 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-18 15:21:53,781 INFO    MainThread:20812 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\ernst\Documents\02-Work\01-Projects\MANTRA\wandb\run-20240518_152153-if2vreum\logs\debug.log
2024-05-18 15:21:53,781 INFO    MainThread:20812 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\ernst\Documents\02-Work\01-Projects\MANTRA\wandb\run-20240518_152153-if2vreum\logs\debug-internal.log
2024-05-18 15:21:53,781 INFO    MainThread:20812 [wandb_init.py:init():564] calling init triggers
2024-05-18 15:21:53,781 INFO    MainThread:20812 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-05-18 15:21:53,781 INFO    MainThread:20812 [wandb_init.py:init():614] starting backend
2024-05-18 15:21:53,781 INFO    MainThread:20812 [wandb_init.py:init():618] setting up manager
2024-05-18 15:21:53,783 INFO    MainThread:20812 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-18 15:21:53,784 INFO    MainThread:20812 [wandb_init.py:init():624] backend started and connected
2024-05-18 15:21:53,791 INFO    MainThread:20812 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-05-18 15:21:53,791 INFO    MainThread:20812 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-18 15:21:53,791 INFO    MainThread:20812 [wandb_init.py:init():716] updated telemetry
2024-05-18 15:21:53,812 INFO    MainThread:20812 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-05-18 15:21:54,262 INFO    MainThread:20812 [wandb_run.py:_on_init():2254] communicating current version
2024-05-18 15:22:24,573 INFO    MainThread:20812 [wandb_init.py:init():800] starting run threads in backend
2024-05-18 15:22:36,694 WARNING MainThread:20812 [wandb_init.py:init():1188] interrupted
Traceback (most recent call last):
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\wandb_init.py", line 1166, in init
    run = wi.init()
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\wandb_init.py", line 811, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-05-18 15:22:37,064 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2024-05-18 15:22:37,064 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Configure stats pid to 20812
2024-05-18 15:22:37,064 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ernst\.config\wandb\settings
2024-05-18 15:22:37,064 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Loading settings from c:\Users\ernst\Documents\02-Work\01-Projects\MANTRA\wandb\settings
2024-05-18 15:22:37,064 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-18 15:22:37,064 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-18 15:22:37,065 INFO    MainThread:20812 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-18 15:22:37,065 INFO    MainThread:20812 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\ernst\Documents\02-Work\01-Projects\MANTRA\wandb\run-20240518_152237-mrrytwin\logs\debug.log
2024-05-18 15:22:37,065 INFO    MainThread:20812 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\ernst\Documents\02-Work\01-Projects\MANTRA\wandb\run-20240518_152237-mrrytwin\logs\debug-internal.log
2024-05-18 15:22:37,065 INFO    MainThread:20812 [wandb_init.py:init():564] calling init triggers
2024-05-18 15:22:37,065 INFO    MainThread:20812 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-05-18 15:22:37,065 INFO    MainThread:20812 [wandb_init.py:init():614] starting backend
2024-05-18 15:22:37,065 INFO    MainThread:20812 [wandb_init.py:init():618] setting up manager
2024-05-18 15:22:37,069 INFO    MainThread:20812 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-18 15:22:37,070 INFO    MainThread:20812 [wandb_init.py:init():624] backend started and connected
2024-05-18 15:22:37,079 INFO    MainThread:20812 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-05-18 15:22:37,080 INFO    MainThread:20812 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-18 15:22:37,080 INFO    MainThread:20812 [wandb_init.py:init():716] updated telemetry
2024-05-18 15:22:37,108 INFO    MainThread:20812 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-05-18 15:22:37,506 INFO    MainThread:20812 [wandb_run.py:_on_init():2254] communicating current version
2024-05-18 15:22:38,523 WARNING MainThread:20812 [wandb_init.py:init():1188] interrupted
Traceback (most recent call last):
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\wandb_init.py", line 1166, in init
    run = wi.init()
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\wandb_init.py", line 798, in init
    run._on_init()
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\wandb_run.py", line 2258, in _on_init
    version_result = version_handle.wait(timeout=30)
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "C:\Users\ernst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
